CREATE TABLE IF NOT EXISTS UT_COLOR
(
    ID INTEGER,
    CONSTRAINT PK_COLOR PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS UT_COLOR_DESCRIPTION
(
    COLOR_ID      INTEGER,
    LANGUAGE_CODE VARCHAR(5),
    NAME          VARCHAR(30) NOT NULL,
    CONSTRAINT PK_COLOR_ID PRIMARY KEY (COLOR_ID, LANGUAGE_CODE),
    CONSTRAINT FK_COLOR FOREIGN KEY (COLOR_ID) REFERENCES UT_COLOR (ID)
);
