DROP TABLE UT_TYPE_DESCRIPTION;

ALTER TABLE UT_CARD DROP CONSTRAINT FK_CARD_TYPE;

DROP TABLE UT_TYPE;

ALTER TABLE UT_CARD
    RENAME COLUMN TYPE_ID TO TYPE;

ALTER TABLE UT_CARD
    ALTER TYPE TYPE VARCHAR(10);

UPDATE UT_CARD
SET TYPE='LEADER'
WHERE TYPE = '0';

UPDATE UT_CARD
SET TYPE='CHARACTER'
WHERE TYPE = '1';

UPDATE UT_CARD
SET TYPE='STAGE'
WHERE TYPE = '2';

UPDATE UT_CARD
SET TYPE='EVENT'
WHERE TYPE = '3';

UPDATE UT_CARD_COLOR
SET COLOR='BLACK'
WHERE COLOR = '4';

UPDATE UT_CARD_COLOR
SET COLOR='YELLOW'
WHERE COLOR = '5';
