ALTER TABLE UT_CARD_IMAGE DROP CONSTRAINT FK_CARD_IMAGE_RARITY;

DROP TABLE UT_RARITY;

ALTER TABLE UT_CARD_IMAGE
    RENAME COLUMN RARITY_ID TO RARITY;

ALTER TABLE UT_CARD_IMAGE
    ALTER RARITY TYPE VARCHAR(10);

UPDATE UT_CARD_IMAGE
SET RARITY='L'
WHERE RARITY = '0';

UPDATE UT_CARD_IMAGE
SET RARITY='C'
WHERE RARITY = '1';

UPDATE UT_CARD_IMAGE
SET RARITY='UC'
WHERE RARITY = '2';

UPDATE UT_CARD_IMAGE
SET RARITY='SR'
WHERE RARITY = '3';

UPDATE UT_CARD_IMAGE
SET RARITY='SEC'
WHERE RARITY = '4';

UPDATE UT_CARD_IMAGE
SET RARITY='R'
WHERE RARITY = '5';

UPDATE UT_CARD_IMAGE
SET RARITY='SP_CARD'
WHERE RARITY = '6';

UPDATE UT_CARD_IMAGE
SET RARITY='P'
WHERE RARITY = '7';
