name: ONE_PIECE_DECK_BUILDER_API_PIPELINE
on:
  push:
    branches:
      - master
      - '*'
jobs:
  tests:
    name: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
  build_push:
    name: Build and Push
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    needs: tests
    environment: PROD
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jonathanjusseaume/one-piece-deck-builder-api:latest
  deploy_prod:
    name: Deploy Prod
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    needs: build_push
    environment: PROD
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "DB_URL=${{ secrets.DB_URL }}" > .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> .env
            echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> .env
            sudo docker stop api || true && sudo docker rm api || true
            sudo docker pull jonathanjusseaume/one-piece-deck-builder-api:latest
            sudo docker run -d -p 8080:8080 --env-file .env --name api --network=host jonathanjusseaume/one-piece-deck-builder-api:latest

